Fix errors with encrypted subdoc arrays on Mongoose v6
As of Mongoose v6, encrypted subdocument arrays lead to the following
error when updating an existing document:

> MongoServerError: Updating the path '…' would create a conflict at '…'

This change circumvents the problem by marking the corresponding schema
paths as unmodified (which should be safe, since those encrypted fields
are not meant to be stored anyway).

Fixes #105